//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Week6_Capstone_TaskListRevisted.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public string Description { get; set; }
        public System.DateTime DueDate { get; set; }
        public int Status { get; set; }
        public string Email { get; set; }
        public int TaskID { get; set; }
        public int UserID { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
